# SPDX-License-Identifier: GPL-2.0-or-later
"""POSIX shell-script emitter; shares command_lines() with the executor."""

from __future__ import annotations

import shlex
from typing import Iterable

from storage.base import Node, ShellCommand


_EOF_MARKER = "SPROV_STDIN_EOF"
_HEADER = """\
#!/bin/sh
# Generated by sprov. Do not edit.
# Re-emit by rerunning: sprov --script <spec.yaml>

# -e: exit on error; -u: error on unset var; -x: trace commands to stderr
# so the operator can follow along and correlate output with failures.
# Heredoc bodies (passphrases) are not printed by -x.
set -eux
"""


class ScriptGenerator:
    """Emit a busybox-compatible POSIX shell script for a prepared node list."""

    def __init__(self, nodes: Iterable[Node]) -> None:
        self.nodes: list[Node] = list(nodes)

    def emit(self) -> str:
        """Return the full script as a single string ending in a newline."""
        parts: list[str] = [_HEADER.rstrip("\n")]
        for node in self.nodes:
            cmds = node.effective_command_lines()
            if not cmds:
                continue
            parts.append("")
            parts.append(f"# === {node.id} ({node.TYPE}) ===")
            for cmd in cmds:
                parts.append(_render_command(cmd))
        parts.append("")
        return "\n".join(parts)


def _render_command(cmd: ShellCommand) -> str:
    """Render a single ShellCommand to its shell-script form."""
    lines: list[str] = []
    if cmd.comment:
        lines.append(f"# {cmd.comment}")
    quoted = " ".join(shlex.quote(a) for a in cmd.argv)
    suffix = "" if cmd.check else " || true"
    if cmd.stdin is None:
        lines.append(f"{quoted}{suffix}")
    else:
        payload = _decode_stdin(cmd.stdin)
        if _EOF_MARKER in payload.splitlines():
            raise ValueError(
                f"stdin payload contains a line equal to the heredoc marker "
                f"{_EOF_MARKER!r}; cannot safely emit"
            )
        lines.append(f"{quoted} <<'{_EOF_MARKER}'{suffix}")
        if not payload.endswith("\n"):
            payload += "\n"
        lines.append(payload + _EOF_MARKER)
    return "\n".join(lines)


def _decode_stdin(data: bytes) -> str:
    try:
        return data.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise ValueError(
            "stdin payload is not UTF-8 decodable; cannot emit as heredoc"
        ) from exc
